### ISSUE TITLE
Make a calculator using js

### ISSUE THREAD

**Issue by Raj8Kumar** [Raj8Kumar/Hacktoberfest-2022#2]

**Comment by sumitbaroniya** [comment]
Please assign me this issue.

**Comment by flow6979** [comment]
Can i contribute to this repo?
thank you

**Comment by Raj8Kumar** [comment]
@sumitbaroniya go through it

**Comment by Raj8Kumar** [comment]
> Can i contribute to this repo? thank you

**Comment by flow6979** [comment]
you reopened this issue? can i contribute?
